REPO_TAGLINE: Modern physics • Quantum Physics • Special Relativity
ASSETS_DIR: .github/readme
CTA_TEXT: Access the full course website
THEME: library
SITE_URL: https://academic-codex.github.io/IF4302212-Fisica-IV

BG_1: "#0B1020"
BG_2: "#0EA5E9"
TEXT_MAIN: "#F0F9FF"
TEXT_MUTED: "#BAE6FD"
ACCENT: "#38BDF8"
CARD_RADIUS: "18"